[2024-04-02 12:59:55,548] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: get_stocks_dag.TSLA scheduled__2024-01-16T00:00:00+00:00 [queued]>
[2024-04-02 12:59:55,558] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: get_stocks_dag.TSLA scheduled__2024-01-16T00:00:00+00:00 [queued]>
[2024-04-02 12:59:55,559] {taskinstance.py:1356} INFO - 
--------------------------------------------------------------------------------
[2024-04-02 12:59:55,559] {taskinstance.py:1357} INFO - Starting attempt 1 of 1
[2024-04-02 12:59:55,559] {taskinstance.py:1358} INFO - 
--------------------------------------------------------------------------------
[2024-04-02 12:59:55,578] {taskinstance.py:1377} INFO - Executing <Task(_PythonDecoratedOperator): TSLA> on 2024-01-16 00:00:00+00:00
[2024-04-02 12:59:55,583] {standard_task_runner.py:52} INFO - Started process 8831 to run task
[2024-04-02 12:59:55,590] {standard_task_runner.py:79} INFO - Running: ['airflow', 'tasks', 'run', 'get_stocks_dag', 'TSLA', 'scheduled__2024-01-16T00:00:00+00:00', '--job-id', '50', '--raw', '--subdir', 'DAGS_FOLDER/get_stocks.py', '--cfg-path', '/tmp/tmpxmdslglx', '--error-file', '/tmp/tmpqt3eh2x2']
[2024-04-02 12:59:55,591] {standard_task_runner.py:80} INFO - Job 50: Subtask TSLA
[2024-04-02 12:59:55,660] {task_command.py:370} INFO - Running <TaskInstance: get_stocks_dag.TSLA scheduled__2024-01-16T00:00:00+00:00 [running]> on host alexmend-virtual-machine
[2024-04-02 12:59:55,736] {taskinstance.py:1569} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=airflow
AIRFLOW_CTX_DAG_ID=get_stocks_dag
AIRFLOW_CTX_TASK_ID=TSLA
AIRFLOW_CTX_EXECUTION_DATE=2024-01-16T00:00:00+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2024-01-16T00:00:00+00:00
[2024-04-02 12:59:56,317] {history.py:222} ERROR - TSLA: No price data found, symbol may be delisted (1h 2024-01-15 -> 2024-01-16)
[2024-04-02 12:59:56,330] {python.py:173} INFO - Done. Returned value was: None
[2024-04-02 12:59:56,353] {taskinstance.py:1395} INFO - Marking task as SUCCESS. dag_id=get_stocks_dag, task_id=TSLA, execution_date=20240116T000000, start_date=20240402T155955, end_date=20240402T155956
[2024-04-02 12:59:56,417] {local_task_job.py:156} INFO - Task exited with return code 0
[2024-04-02 12:59:56,460] {local_task_job.py:273} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-04-02 17:17:13,346] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: get_stocks_dag.TSLA scheduled__2024-01-16T00:00:00+00:00 [queued]>
[2024-04-02 17:17:13,865] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: get_stocks_dag.TSLA scheduled__2024-01-16T00:00:00+00:00 [queued]>
[2024-04-02 17:17:13,865] {taskinstance.py:1356} INFO - 
--------------------------------------------------------------------------------
[2024-04-02 17:17:13,865] {taskinstance.py:1357} INFO - Starting attempt 1 of 1
[2024-04-02 17:17:13,865] {taskinstance.py:1358} INFO - 
--------------------------------------------------------------------------------
[2024-04-02 17:17:14,322] {taskinstance.py:1377} INFO - Executing <Task(_PythonDecoratedOperator): TSLA> on 2024-01-16 00:00:00+00:00
[2024-04-02 17:17:14,355] {standard_task_runner.py:52} INFO - Started process 4460 to run task
[2024-04-02 17:17:15,571] {standard_task_runner.py:79} INFO - Running: ['airflow', 'tasks', 'run', 'get_stocks_dag', 'TSLA', 'scheduled__2024-01-16T00:00:00+00:00', '--job-id', '31', '--raw', '--subdir', 'DAGS_FOLDER/get_stocks.py', '--cfg-path', '/tmp/tmpf97h98tz', '--error-file', '/tmp/tmpp0a90o5l']
[2024-04-02 17:17:15,630] {standard_task_runner.py:80} INFO - Job 31: Subtask TSLA
[2024-04-02 17:17:18,063] {task_command.py:370} INFO - Running <TaskInstance: get_stocks_dag.TSLA scheduled__2024-01-16T00:00:00+00:00 [running]> on host alexmend-virtual-machine
[2024-04-02 17:17:19,549] {taskinstance.py:1569} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=airflow
AIRFLOW_CTX_DAG_ID=get_stocks_dag
AIRFLOW_CTX_TASK_ID=TSLA
AIRFLOW_CTX_EXECUTION_DATE=2024-01-16T00:00:00+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2024-01-16T00:00:00+00:00
[2024-04-02 17:17:21,918] {taskinstance.py:1889} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/alexmend/Documents/airflowalex/venv/lib/python3.9/site-packages/airflow/decorators/base.py", line 179, in execute
    return_value = super().execute(context)
  File "/home/alexmend/Documents/airflowalex/venv/lib/python3.9/site-packages/airflow/operators/python.py", line 171, in execute
    return_value = self.execute_callable()
  File "/home/alexmend/Documents/airflowalex/venv/lib/python3.9/site-packages/airflow/operators/python.py", line 189, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/home/alexmend/Documents/airflowalex/dags/get_stocks.py", line 18, in get_history
    yfinance.Ticker(ticker).history(
  File "/home/alexmend/Documents/airflowalex/venv/lib/python3.9/site-packages/yfinance/utils.py", line 103, in wrapper
    result = func(*args, **kwargs)
  File "/home/alexmend/Documents/airflowalex/venv/lib/python3.9/site-packages/yfinance/base.py", line 77, in history
    return self._lazy_load_price_history().history(*args, **kwargs)
  File "/home/alexmend/Documents/airflowalex/venv/lib/python3.9/site-packages/yfinance/utils.py", line 103, in wrapper
    result = func(*args, **kwargs)
  File "/home/alexmend/Documents/airflowalex/venv/lib/python3.9/site-packages/yfinance/scrapers/history.py", line 226, in history
    logger.debug(f'{self.ticker}: yfinance received OHLC data: {quotes.index[0]} -> {quotes.index[-1]}')
  File "/home/alexmend/Documents/airflowalex/venv/lib/python3.9/site-packages/pandas/core/indexes/base.py", line 5389, in __getitem__
    return getitem(key)
  File "/home/alexmend/Documents/airflowalex/venv/lib/python3.9/site-packages/pandas/core/arrays/datetimelike.py", line 379, in __getitem__
    result = cast("Union[Self, DTScalarOrNaT]", super().__getitem__(key))
  File "/home/alexmend/Documents/airflowalex/venv/lib/python3.9/site-packages/pandas/core/arrays/_mixins.py", line 284, in __getitem__
    result = self._ndarray[key]
IndexError: index 0 is out of bounds for axis 0 with size 0
[2024-04-02 17:17:22,172] {taskinstance.py:1395} INFO - Marking task as FAILED. dag_id=get_stocks_dag, task_id=TSLA, execution_date=20240116T000000, start_date=20240402T201713, end_date=20240402T201722
[2024-04-02 17:17:22,380] {standard_task_runner.py:92} ERROR - Failed to execute job 31 for task TSLA (index 0 is out of bounds for axis 0 with size 0; 4460)
[2024-04-02 17:17:22,529] {local_task_job.py:156} INFO - Task exited with return code 1
[2024-04-02 17:17:22,920] {local_task_job.py:273} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-04-02 17:42:45,147] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: get_stocks_dag.TSLA scheduled__2024-01-16T00:00:00+00:00 [queued]>
[2024-04-02 17:42:45,157] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: get_stocks_dag.TSLA scheduled__2024-01-16T00:00:00+00:00 [queued]>
[2024-04-02 17:42:45,157] {taskinstance.py:1356} INFO - 
--------------------------------------------------------------------------------
[2024-04-02 17:42:45,157] {taskinstance.py:1357} INFO - Starting attempt 1 of 1
[2024-04-02 17:42:45,157] {taskinstance.py:1358} INFO - 
--------------------------------------------------------------------------------
[2024-04-02 17:42:45,172] {taskinstance.py:1377} INFO - Executing <Task(_PythonDecoratedOperator): TSLA> on 2024-01-16 00:00:00+00:00
[2024-04-02 17:42:45,178] {standard_task_runner.py:52} INFO - Started process 19011 to run task
[2024-04-02 17:42:45,185] {standard_task_runner.py:79} INFO - Running: ['airflow', 'tasks', 'run', 'get_stocks_dag', 'TSLA', 'scheduled__2024-01-16T00:00:00+00:00', '--job-id', '291', '--raw', '--subdir', 'DAGS_FOLDER/get_stocks.py', '--cfg-path', '/tmp/tmpx9hqjedb', '--error-file', '/tmp/tmp1ruesfq_']
[2024-04-02 17:42:45,187] {standard_task_runner.py:80} INFO - Job 291: Subtask TSLA
[2024-04-02 17:42:45,310] {task_command.py:370} INFO - Running <TaskInstance: get_stocks_dag.TSLA scheduled__2024-01-16T00:00:00+00:00 [running]> on host alexmend-virtual-machine
[2024-04-02 17:42:45,431] {taskinstance.py:1569} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=airflow
AIRFLOW_CTX_DAG_ID=get_stocks_dag
AIRFLOW_CTX_TASK_ID=TSLA
AIRFLOW_CTX_EXECUTION_DATE=2024-01-16T00:00:00+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2024-01-16T00:00:00+00:00
[2024-04-02 17:42:46,063] {taskinstance.py:1889} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/alexmend/Documents/airflowalex/venv/lib/python3.9/site-packages/airflow/decorators/base.py", line 179, in execute
    return_value = super().execute(context)
  File "/home/alexmend/Documents/airflowalex/venv/lib/python3.9/site-packages/airflow/operators/python.py", line 171, in execute
    return_value = self.execute_callable()
  File "/home/alexmend/Documents/airflowalex/venv/lib/python3.9/site-packages/airflow/operators/python.py", line 189, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/home/alexmend/Documents/airflowalex/dags/get_stocks.py", line 18, in get_history
    yfinance.Ticker(ticker).history(
  File "/home/alexmend/Documents/airflowalex/venv/lib/python3.9/site-packages/yfinance/utils.py", line 103, in wrapper
    result = func(*args, **kwargs)
  File "/home/alexmend/Documents/airflowalex/venv/lib/python3.9/site-packages/yfinance/base.py", line 77, in history
    return self._lazy_load_price_history().history(*args, **kwargs)
  File "/home/alexmend/Documents/airflowalex/venv/lib/python3.9/site-packages/yfinance/utils.py", line 103, in wrapper
    result = func(*args, **kwargs)
  File "/home/alexmend/Documents/airflowalex/venv/lib/python3.9/site-packages/yfinance/scrapers/history.py", line 226, in history
    logger.debug(f'{self.ticker}: yfinance received OHLC data: {quotes.index[0]} -> {quotes.index[-1]}')
  File "/home/alexmend/Documents/airflowalex/venv/lib/python3.9/site-packages/pandas/core/indexes/base.py", line 5389, in __getitem__
    return getitem(key)
  File "/home/alexmend/Documents/airflowalex/venv/lib/python3.9/site-packages/pandas/core/arrays/datetimelike.py", line 379, in __getitem__
    result = cast("Union[Self, DTScalarOrNaT]", super().__getitem__(key))
  File "/home/alexmend/Documents/airflowalex/venv/lib/python3.9/site-packages/pandas/core/arrays/_mixins.py", line 284, in __getitem__
    result = self._ndarray[key]
IndexError: index 0 is out of bounds for axis 0 with size 0
[2024-04-02 17:42:46,087] {taskinstance.py:1395} INFO - Marking task as FAILED. dag_id=get_stocks_dag, task_id=TSLA, execution_date=20240116T000000, start_date=20240402T204245, end_date=20240402T204246
[2024-04-02 17:42:46,107] {standard_task_runner.py:92} ERROR - Failed to execute job 291 for task TSLA (index 0 is out of bounds for axis 0 with size 0; 19011)
[2024-04-02 17:42:46,127] {local_task_job.py:156} INFO - Task exited with return code 1
[2024-04-02 17:42:46,189] {local_task_job.py:273} INFO - 0 downstream tasks scheduled from follow-on schedule check
