[2024-04-02 12:59:47,686] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: get_stocks_dag.MSFT scheduled__2024-01-16T00:00:00+00:00 [queued]>
[2024-04-02 12:59:47,697] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: get_stocks_dag.MSFT scheduled__2024-01-16T00:00:00+00:00 [queued]>
[2024-04-02 12:59:47,698] {taskinstance.py:1356} INFO - 
--------------------------------------------------------------------------------
[2024-04-02 12:59:47,698] {taskinstance.py:1357} INFO - Starting attempt 1 of 1
[2024-04-02 12:59:47,698] {taskinstance.py:1358} INFO - 
--------------------------------------------------------------------------------
[2024-04-02 12:59:47,719] {taskinstance.py:1377} INFO - Executing <Task(_PythonDecoratedOperator): MSFT> on 2024-01-16 00:00:00+00:00
[2024-04-02 12:59:47,729] {standard_task_runner.py:52} INFO - Started process 8793 to run task
[2024-04-02 12:59:47,738] {standard_task_runner.py:79} INFO - Running: ['airflow', 'tasks', 'run', 'get_stocks_dag', 'MSFT', 'scheduled__2024-01-16T00:00:00+00:00', '--job-id', '48', '--raw', '--subdir', 'DAGS_FOLDER/get_stocks.py', '--cfg-path', '/tmp/tmp0_rzkw0r', '--error-file', '/tmp/tmpv3l1pxau']
[2024-04-02 12:59:47,739] {standard_task_runner.py:80} INFO - Job 48: Subtask MSFT
[2024-04-02 12:59:47,844] {task_command.py:370} INFO - Running <TaskInstance: get_stocks_dag.MSFT scheduled__2024-01-16T00:00:00+00:00 [running]> on host alexmend-virtual-machine
[2024-04-02 12:59:47,962] {taskinstance.py:1569} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=airflow
AIRFLOW_CTX_DAG_ID=get_stocks_dag
AIRFLOW_CTX_TASK_ID=MSFT
AIRFLOW_CTX_EXECUTION_DATE=2024-01-16T00:00:00+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2024-01-16T00:00:00+00:00
[2024-04-02 12:59:48,699] {history.py:222} ERROR - MSFT: No price data found, symbol may be delisted (1h 2024-01-15 -> 2024-01-16)
[2024-04-02 12:59:48,711] {python.py:173} INFO - Done. Returned value was: None
[2024-04-02 12:59:48,733] {taskinstance.py:1395} INFO - Marking task as SUCCESS. dag_id=get_stocks_dag, task_id=MSFT, execution_date=20240116T000000, start_date=20240402T155947, end_date=20240402T155948
[2024-04-02 12:59:48,769] {local_task_job.py:156} INFO - Task exited with return code 0
[2024-04-02 12:59:48,818] {local_task_job.py:273} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-04-02 17:17:06,509] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: get_stocks_dag.MSFT scheduled__2024-01-16T00:00:00+00:00 [queued]>
[2024-04-02 17:17:06,610] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: get_stocks_dag.MSFT scheduled__2024-01-16T00:00:00+00:00 [queued]>
[2024-04-02 17:17:06,611] {taskinstance.py:1356} INFO - 
--------------------------------------------------------------------------------
[2024-04-02 17:17:06,611] {taskinstance.py:1357} INFO - Starting attempt 1 of 1
[2024-04-02 17:17:06,611] {taskinstance.py:1358} INFO - 
--------------------------------------------------------------------------------
[2024-04-02 17:17:07,336] {taskinstance.py:1377} INFO - Executing <Task(_PythonDecoratedOperator): MSFT> on 2024-01-16 00:00:00+00:00
[2024-04-02 17:17:09,095] {standard_task_runner.py:79} INFO - Running: ['airflow', 'tasks', 'run', 'get_stocks_dag', 'MSFT', 'scheduled__2024-01-16T00:00:00+00:00', '--job-id', '29', '--raw', '--subdir', 'DAGS_FOLDER/get_stocks.py', '--cfg-path', '/tmp/tmp6s16y0x7', '--error-file', '/tmp/tmpgu66ecku']
[2024-04-02 17:17:09,336] {standard_task_runner.py:80} INFO - Job 29: Subtask MSFT
[2024-04-02 17:17:08,200] {standard_task_runner.py:52} INFO - Started process 4387 to run task
[2024-04-02 17:17:14,090] {task_command.py:370} INFO - Running <TaskInstance: get_stocks_dag.MSFT scheduled__2024-01-16T00:00:00+00:00 [running]> on host alexmend-virtual-machine
[2024-04-02 17:17:16,249] {taskinstance.py:1569} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=airflow
AIRFLOW_CTX_DAG_ID=get_stocks_dag
AIRFLOW_CTX_TASK_ID=MSFT
AIRFLOW_CTX_EXECUTION_DATE=2024-01-16T00:00:00+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2024-01-16T00:00:00+00:00
[2024-04-02 17:17:19,497] {taskinstance.py:1889} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/alexmend/Documents/airflowalex/venv/lib/python3.9/site-packages/airflow/decorators/base.py", line 179, in execute
    return_value = super().execute(context)
  File "/home/alexmend/Documents/airflowalex/venv/lib/python3.9/site-packages/airflow/operators/python.py", line 171, in execute
    return_value = self.execute_callable()
  File "/home/alexmend/Documents/airflowalex/venv/lib/python3.9/site-packages/airflow/operators/python.py", line 189, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/home/alexmend/Documents/airflowalex/dags/get_stocks.py", line 18, in get_history
    yfinance.Ticker(ticker).history(
  File "/home/alexmend/Documents/airflowalex/venv/lib/python3.9/site-packages/yfinance/utils.py", line 103, in wrapper
    result = func(*args, **kwargs)
  File "/home/alexmend/Documents/airflowalex/venv/lib/python3.9/site-packages/yfinance/base.py", line 77, in history
    return self._lazy_load_price_history().history(*args, **kwargs)
  File "/home/alexmend/Documents/airflowalex/venv/lib/python3.9/site-packages/yfinance/utils.py", line 103, in wrapper
    result = func(*args, **kwargs)
  File "/home/alexmend/Documents/airflowalex/venv/lib/python3.9/site-packages/yfinance/scrapers/history.py", line 226, in history
    logger.debug(f'{self.ticker}: yfinance received OHLC data: {quotes.index[0]} -> {quotes.index[-1]}')
  File "/home/alexmend/Documents/airflowalex/venv/lib/python3.9/site-packages/pandas/core/indexes/base.py", line 5389, in __getitem__
    return getitem(key)
  File "/home/alexmend/Documents/airflowalex/venv/lib/python3.9/site-packages/pandas/core/arrays/datetimelike.py", line 379, in __getitem__
    result = cast("Union[Self, DTScalarOrNaT]", super().__getitem__(key))
  File "/home/alexmend/Documents/airflowalex/venv/lib/python3.9/site-packages/pandas/core/arrays/_mixins.py", line 284, in __getitem__
    result = self._ndarray[key]
IndexError: index 0 is out of bounds for axis 0 with size 0
[2024-04-02 17:17:19,825] {taskinstance.py:1395} INFO - Marking task as FAILED. dag_id=get_stocks_dag, task_id=MSFT, execution_date=20240116T000000, start_date=20240402T201706, end_date=20240402T201719
[2024-04-02 17:17:20,045] {standard_task_runner.py:92} ERROR - Failed to execute job 29 for task MSFT (index 0 is out of bounds for axis 0 with size 0; 4387)
[2024-04-02 17:17:20,250] {local_task_job.py:156} INFO - Task exited with return code 1
[2024-04-02 17:17:20,505] {local_task_job.py:273} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-04-02 17:42:48,986] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: get_stocks_dag.MSFT scheduled__2024-01-16T00:00:00+00:00 [queued]>
[2024-04-02 17:42:48,998] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: get_stocks_dag.MSFT scheduled__2024-01-16T00:00:00+00:00 [queued]>
[2024-04-02 17:42:48,998] {taskinstance.py:1356} INFO - 
--------------------------------------------------------------------------------
[2024-04-02 17:42:48,998] {taskinstance.py:1357} INFO - Starting attempt 1 of 1
[2024-04-02 17:42:48,998] {taskinstance.py:1358} INFO - 
--------------------------------------------------------------------------------
[2024-04-02 17:42:49,014] {taskinstance.py:1377} INFO - Executing <Task(_PythonDecoratedOperator): MSFT> on 2024-01-16 00:00:00+00:00
[2024-04-02 17:42:49,021] {standard_task_runner.py:52} INFO - Started process 19068 to run task
[2024-04-02 17:42:49,028] {standard_task_runner.py:79} INFO - Running: ['airflow', 'tasks', 'run', 'get_stocks_dag', 'MSFT', 'scheduled__2024-01-16T00:00:00+00:00', '--job-id', '294', '--raw', '--subdir', 'DAGS_FOLDER/get_stocks.py', '--cfg-path', '/tmp/tmp49n8oqsd', '--error-file', '/tmp/tmp4qz9qm3j']
[2024-04-02 17:42:49,029] {standard_task_runner.py:80} INFO - Job 294: Subtask MSFT
[2024-04-02 17:42:49,138] {task_command.py:370} INFO - Running <TaskInstance: get_stocks_dag.MSFT scheduled__2024-01-16T00:00:00+00:00 [running]> on host alexmend-virtual-machine
[2024-04-02 17:42:49,295] {taskinstance.py:1569} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=airflow
AIRFLOW_CTX_DAG_ID=get_stocks_dag
AIRFLOW_CTX_TASK_ID=MSFT
AIRFLOW_CTX_EXECUTION_DATE=2024-01-16T00:00:00+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2024-01-16T00:00:00+00:00
[2024-04-02 17:42:50,668] {taskinstance.py:1889} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/alexmend/Documents/airflowalex/venv/lib/python3.9/site-packages/airflow/decorators/base.py", line 179, in execute
    return_value = super().execute(context)
  File "/home/alexmend/Documents/airflowalex/venv/lib/python3.9/site-packages/airflow/operators/python.py", line 171, in execute
    return_value = self.execute_callable()
  File "/home/alexmend/Documents/airflowalex/venv/lib/python3.9/site-packages/airflow/operators/python.py", line 189, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/home/alexmend/Documents/airflowalex/dags/get_stocks.py", line 18, in get_history
    yfinance.Ticker(ticker).history(
  File "/home/alexmend/Documents/airflowalex/venv/lib/python3.9/site-packages/yfinance/utils.py", line 103, in wrapper
    result = func(*args, **kwargs)
  File "/home/alexmend/Documents/airflowalex/venv/lib/python3.9/site-packages/yfinance/base.py", line 77, in history
    return self._lazy_load_price_history().history(*args, **kwargs)
  File "/home/alexmend/Documents/airflowalex/venv/lib/python3.9/site-packages/yfinance/utils.py", line 103, in wrapper
    result = func(*args, **kwargs)
  File "/home/alexmend/Documents/airflowalex/venv/lib/python3.9/site-packages/yfinance/scrapers/history.py", line 226, in history
    logger.debug(f'{self.ticker}: yfinance received OHLC data: {quotes.index[0]} -> {quotes.index[-1]}')
  File "/home/alexmend/Documents/airflowalex/venv/lib/python3.9/site-packages/pandas/core/indexes/base.py", line 5389, in __getitem__
    return getitem(key)
  File "/home/alexmend/Documents/airflowalex/venv/lib/python3.9/site-packages/pandas/core/arrays/datetimelike.py", line 379, in __getitem__
    result = cast("Union[Self, DTScalarOrNaT]", super().__getitem__(key))
  File "/home/alexmend/Documents/airflowalex/venv/lib/python3.9/site-packages/pandas/core/arrays/_mixins.py", line 284, in __getitem__
    result = self._ndarray[key]
IndexError: index 0 is out of bounds for axis 0 with size 0
[2024-04-02 17:42:50,696] {taskinstance.py:1395} INFO - Marking task as FAILED. dag_id=get_stocks_dag, task_id=MSFT, execution_date=20240116T000000, start_date=20240402T204248, end_date=20240402T204250
[2024-04-02 17:42:50,713] {standard_task_runner.py:92} ERROR - Failed to execute job 294 for task MSFT (index 0 is out of bounds for axis 0 with size 0; 19068)
[2024-04-02 17:42:50,739] {local_task_job.py:156} INFO - Task exited with return code 1
[2024-04-02 17:42:50,793] {local_task_job.py:273} INFO - 0 downstream tasks scheduled from follow-on schedule check
