[2024-04-02 13:06:53,664] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: get_stocks_dag.TSLA scheduled__2024-02-20T00:00:00+00:00 [queued]>
[2024-04-02 13:06:53,672] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: get_stocks_dag.TSLA scheduled__2024-02-20T00:00:00+00:00 [queued]>
[2024-04-02 13:06:53,672] {taskinstance.py:1356} INFO - 
--------------------------------------------------------------------------------
[2024-04-02 13:06:53,673] {taskinstance.py:1357} INFO - Starting attempt 1 of 1
[2024-04-02 13:06:53,673] {taskinstance.py:1358} INFO - 
--------------------------------------------------------------------------------
[2024-04-02 13:06:53,695] {taskinstance.py:1377} INFO - Executing <Task(_PythonDecoratedOperator): TSLA> on 2024-02-20 00:00:00+00:00
[2024-04-02 13:06:53,701] {standard_task_runner.py:52} INFO - Started process 11288 to run task
[2024-04-02 13:06:53,707] {standard_task_runner.py:79} INFO - Running: ['airflow', 'tasks', 'run', 'get_stocks_dag', 'TSLA', 'scheduled__2024-02-20T00:00:00+00:00', '--job-id', '150', '--raw', '--subdir', 'DAGS_FOLDER/get_stocks.py', '--cfg-path', '/tmp/tmpvrijbvc5', '--error-file', '/tmp/tmpyx280s3s']
[2024-04-02 13:06:53,708] {standard_task_runner.py:80} INFO - Job 150: Subtask TSLA
[2024-04-02 13:06:53,769] {task_command.py:370} INFO - Running <TaskInstance: get_stocks_dag.TSLA scheduled__2024-02-20T00:00:00+00:00 [running]> on host alexmend-virtual-machine
[2024-04-02 13:06:53,854] {taskinstance.py:1569} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=airflow
AIRFLOW_CTX_DAG_ID=get_stocks_dag
AIRFLOW_CTX_TASK_ID=TSLA
AIRFLOW_CTX_EXECUTION_DATE=2024-02-20T00:00:00+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2024-02-20T00:00:00+00:00
[2024-04-02 13:06:54,482] {history.py:222} ERROR - TSLA: No price data found, symbol may be delisted (1h 2024-02-19 -> 2024-02-20)
[2024-04-02 13:06:54,485] {python.py:173} INFO - Done. Returned value was: None
[2024-04-02 13:06:54,491] {taskinstance.py:1395} INFO - Marking task as SUCCESS. dag_id=get_stocks_dag, task_id=TSLA, execution_date=20240220T000000, start_date=20240402T160653, end_date=20240402T160654
[2024-04-02 13:06:54,523] {local_task_job.py:156} INFO - Task exited with return code 0
[2024-04-02 13:06:54,544] {local_task_job.py:273} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-04-02 17:18:49,389] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: get_stocks_dag.TSLA scheduled__2024-02-20T00:00:00+00:00 [queued]>
[2024-04-02 17:18:49,480] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: get_stocks_dag.TSLA scheduled__2024-02-20T00:00:00+00:00 [queued]>
[2024-04-02 17:18:49,480] {taskinstance.py:1356} INFO - 
--------------------------------------------------------------------------------
[2024-04-02 17:18:49,480] {taskinstance.py:1357} INFO - Starting attempt 1 of 1
[2024-04-02 17:18:49,481] {taskinstance.py:1358} INFO - 
--------------------------------------------------------------------------------
[2024-04-02 17:18:49,643] {taskinstance.py:1377} INFO - Executing <Task(_PythonDecoratedOperator): TSLA> on 2024-02-20 00:00:00+00:00
[2024-04-02 17:18:49,710] {standard_task_runner.py:52} INFO - Started process 7091 to run task
[2024-04-02 17:18:49,813] {standard_task_runner.py:79} INFO - Running: ['airflow', 'tasks', 'run', 'get_stocks_dag', 'TSLA', 'scheduled__2024-02-20T00:00:00+00:00', '--job-id', '132', '--raw', '--subdir', 'DAGS_FOLDER/get_stocks.py', '--cfg-path', '/tmp/tmpdzfsrqzy', '--error-file', '/tmp/tmpsgr2pnfd']
[2024-04-02 17:18:49,815] {standard_task_runner.py:80} INFO - Job 132: Subtask TSLA
[2024-04-02 17:18:50,383] {task_command.py:370} INFO - Running <TaskInstance: get_stocks_dag.TSLA scheduled__2024-02-20T00:00:00+00:00 [running]> on host alexmend-virtual-machine
[2024-04-02 17:18:50,865] {taskinstance.py:1569} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=airflow
AIRFLOW_CTX_DAG_ID=get_stocks_dag
AIRFLOW_CTX_TASK_ID=TSLA
AIRFLOW_CTX_EXECUTION_DATE=2024-02-20T00:00:00+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2024-02-20T00:00:00+00:00
[2024-04-02 17:18:51,954] {taskinstance.py:1889} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/alexmend/Documents/airflowalex/venv/lib/python3.9/site-packages/airflow/decorators/base.py", line 179, in execute
    return_value = super().execute(context)
  File "/home/alexmend/Documents/airflowalex/venv/lib/python3.9/site-packages/airflow/operators/python.py", line 171, in execute
    return_value = self.execute_callable()
  File "/home/alexmend/Documents/airflowalex/venv/lib/python3.9/site-packages/airflow/operators/python.py", line 189, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/home/alexmend/Documents/airflowalex/dags/get_stocks.py", line 18, in get_history
    yfinance.Ticker(ticker).history(
  File "/home/alexmend/Documents/airflowalex/venv/lib/python3.9/site-packages/yfinance/utils.py", line 103, in wrapper
    result = func(*args, **kwargs)
  File "/home/alexmend/Documents/airflowalex/venv/lib/python3.9/site-packages/yfinance/base.py", line 77, in history
    return self._lazy_load_price_history().history(*args, **kwargs)
  File "/home/alexmend/Documents/airflowalex/venv/lib/python3.9/site-packages/yfinance/utils.py", line 103, in wrapper
    result = func(*args, **kwargs)
  File "/home/alexmend/Documents/airflowalex/venv/lib/python3.9/site-packages/yfinance/scrapers/history.py", line 226, in history
    logger.debug(f'{self.ticker}: yfinance received OHLC data: {quotes.index[0]} -> {quotes.index[-1]}')
  File "/home/alexmend/Documents/airflowalex/venv/lib/python3.9/site-packages/pandas/core/indexes/base.py", line 5389, in __getitem__
    return getitem(key)
  File "/home/alexmend/Documents/airflowalex/venv/lib/python3.9/site-packages/pandas/core/arrays/datetimelike.py", line 379, in __getitem__
    result = cast("Union[Self, DTScalarOrNaT]", super().__getitem__(key))
  File "/home/alexmend/Documents/airflowalex/venv/lib/python3.9/site-packages/pandas/core/arrays/_mixins.py", line 284, in __getitem__
    result = self._ndarray[key]
IndexError: index 0 is out of bounds for axis 0 with size 0
[2024-04-02 17:18:52,018] {taskinstance.py:1395} INFO - Marking task as FAILED. dag_id=get_stocks_dag, task_id=TSLA, execution_date=20240220T000000, start_date=20240402T201849, end_date=20240402T201852
[2024-04-02 17:18:52,136] {standard_task_runner.py:92} ERROR - Failed to execute job 132 for task TSLA (index 0 is out of bounds for axis 0 with size 0; 7091)
[2024-04-02 17:18:52,281] {local_task_job.py:156} INFO - Task exited with return code 1
[2024-04-02 17:18:52,419] {local_task_job.py:273} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-04-02 17:45:12,117] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: get_stocks_dag.TSLA scheduled__2024-02-20T00:00:00+00:00 [queued]>
[2024-04-02 17:45:12,134] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: get_stocks_dag.TSLA scheduled__2024-02-20T00:00:00+00:00 [queued]>
[2024-04-02 17:45:12,134] {taskinstance.py:1356} INFO - 
--------------------------------------------------------------------------------
[2024-04-02 17:45:12,134] {taskinstance.py:1357} INFO - Starting attempt 1 of 1
[2024-04-02 17:45:12,134] {taskinstance.py:1358} INFO - 
--------------------------------------------------------------------------------
[2024-04-02 17:45:12,168] {taskinstance.py:1377} INFO - Executing <Task(_PythonDecoratedOperator): TSLA> on 2024-02-20 00:00:00+00:00
[2024-04-02 17:45:12,175] {standard_task_runner.py:52} INFO - Started process 22023 to run task
[2024-04-02 17:45:12,183] {standard_task_runner.py:79} INFO - Running: ['airflow', 'tasks', 'run', 'get_stocks_dag', 'TSLA', 'scheduled__2024-02-20T00:00:00+00:00', '--job-id', '394', '--raw', '--subdir', 'DAGS_FOLDER/get_stocks.py', '--cfg-path', '/tmp/tmpdfxos199', '--error-file', '/tmp/tmply31m2ny']
[2024-04-02 17:45:12,184] {standard_task_runner.py:80} INFO - Job 394: Subtask TSLA
[2024-04-02 17:45:12,291] {task_command.py:370} INFO - Running <TaskInstance: get_stocks_dag.TSLA scheduled__2024-02-20T00:00:00+00:00 [running]> on host alexmend-virtual-machine
[2024-04-02 17:45:12,394] {taskinstance.py:1569} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=airflow
AIRFLOW_CTX_DAG_ID=get_stocks_dag
AIRFLOW_CTX_TASK_ID=TSLA
AIRFLOW_CTX_EXECUTION_DATE=2024-02-20T00:00:00+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2024-02-20T00:00:00+00:00
[2024-04-02 17:45:12,969] {taskinstance.py:1889} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/alexmend/Documents/airflowalex/venv/lib/python3.9/site-packages/airflow/decorators/base.py", line 179, in execute
    return_value = super().execute(context)
  File "/home/alexmend/Documents/airflowalex/venv/lib/python3.9/site-packages/airflow/operators/python.py", line 171, in execute
    return_value = self.execute_callable()
  File "/home/alexmend/Documents/airflowalex/venv/lib/python3.9/site-packages/airflow/operators/python.py", line 189, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/home/alexmend/Documents/airflowalex/dags/get_stocks.py", line 18, in get_history
    yfinance.Ticker(ticker).history(
  File "/home/alexmend/Documents/airflowalex/venv/lib/python3.9/site-packages/yfinance/utils.py", line 103, in wrapper
    result = func(*args, **kwargs)
  File "/home/alexmend/Documents/airflowalex/venv/lib/python3.9/site-packages/yfinance/base.py", line 77, in history
    return self._lazy_load_price_history().history(*args, **kwargs)
  File "/home/alexmend/Documents/airflowalex/venv/lib/python3.9/site-packages/yfinance/utils.py", line 103, in wrapper
    result = func(*args, **kwargs)
  File "/home/alexmend/Documents/airflowalex/venv/lib/python3.9/site-packages/yfinance/scrapers/history.py", line 226, in history
    logger.debug(f'{self.ticker}: yfinance received OHLC data: {quotes.index[0]} -> {quotes.index[-1]}')
  File "/home/alexmend/Documents/airflowalex/venv/lib/python3.9/site-packages/pandas/core/indexes/base.py", line 5389, in __getitem__
    return getitem(key)
  File "/home/alexmend/Documents/airflowalex/venv/lib/python3.9/site-packages/pandas/core/arrays/datetimelike.py", line 379, in __getitem__
    result = cast("Union[Self, DTScalarOrNaT]", super().__getitem__(key))
  File "/home/alexmend/Documents/airflowalex/venv/lib/python3.9/site-packages/pandas/core/arrays/_mixins.py", line 284, in __getitem__
    result = self._ndarray[key]
IndexError: index 0 is out of bounds for axis 0 with size 0
[2024-04-02 17:45:12,996] {taskinstance.py:1395} INFO - Marking task as FAILED. dag_id=get_stocks_dag, task_id=TSLA, execution_date=20240220T000000, start_date=20240402T204512, end_date=20240402T204512
[2024-04-02 17:45:13,014] {standard_task_runner.py:92} ERROR - Failed to execute job 394 for task TSLA (index 0 is out of bounds for axis 0 with size 0; 22023)
[2024-04-02 17:45:13,038] {local_task_job.py:156} INFO - Task exited with return code 1
[2024-04-02 17:45:13,101] {local_task_job.py:273} INFO - 0 downstream tasks scheduled from follow-on schedule check
