[2024-04-02 12:59:51,785] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: get_stocks_dag.GOOG scheduled__2024-01-16T00:00:00+00:00 [queued]>
[2024-04-02 12:59:51,795] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: get_stocks_dag.GOOG scheduled__2024-01-16T00:00:00+00:00 [queued]>
[2024-04-02 12:59:51,795] {taskinstance.py:1356} INFO - 
--------------------------------------------------------------------------------
[2024-04-02 12:59:51,796] {taskinstance.py:1357} INFO - Starting attempt 1 of 1
[2024-04-02 12:59:51,796] {taskinstance.py:1358} INFO - 
--------------------------------------------------------------------------------
[2024-04-02 12:59:51,814] {taskinstance.py:1377} INFO - Executing <Task(_PythonDecoratedOperator): GOOG> on 2024-01-16 00:00:00+00:00
[2024-04-02 12:59:51,820] {standard_task_runner.py:52} INFO - Started process 8810 to run task
[2024-04-02 12:59:51,827] {standard_task_runner.py:79} INFO - Running: ['airflow', 'tasks', 'run', 'get_stocks_dag', 'GOOG', 'scheduled__2024-01-16T00:00:00+00:00', '--job-id', '49', '--raw', '--subdir', 'DAGS_FOLDER/get_stocks.py', '--cfg-path', '/tmp/tmpdb1_7iz2', '--error-file', '/tmp/tmpcm_gv_1n']
[2024-04-02 12:59:51,828] {standard_task_runner.py:80} INFO - Job 49: Subtask GOOG
[2024-04-02 12:59:51,912] {task_command.py:370} INFO - Running <TaskInstance: get_stocks_dag.GOOG scheduled__2024-01-16T00:00:00+00:00 [running]> on host alexmend-virtual-machine
[2024-04-02 12:59:51,978] {taskinstance.py:1569} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=airflow
AIRFLOW_CTX_DAG_ID=get_stocks_dag
AIRFLOW_CTX_TASK_ID=GOOG
AIRFLOW_CTX_EXECUTION_DATE=2024-01-16T00:00:00+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2024-01-16T00:00:00+00:00
[2024-04-02 12:59:52,641] {history.py:222} ERROR - GOOG: No price data found, symbol may be delisted (1h 2024-01-15 -> 2024-01-16)
[2024-04-02 12:59:52,656] {python.py:173} INFO - Done. Returned value was: None
[2024-04-02 12:59:52,680] {taskinstance.py:1395} INFO - Marking task as SUCCESS. dag_id=get_stocks_dag, task_id=GOOG, execution_date=20240116T000000, start_date=20240402T155951, end_date=20240402T155952
[2024-04-02 12:59:52,722] {local_task_job.py:156} INFO - Task exited with return code 0
[2024-04-02 12:59:52,761] {local_task_job.py:273} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-04-02 17:17:02,074] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: get_stocks_dag.GOOG scheduled__2024-01-16T00:00:00+00:00 [queued]>
[2024-04-02 17:17:02,285] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: get_stocks_dag.GOOG scheduled__2024-01-16T00:00:00+00:00 [queued]>
[2024-04-02 17:17:02,285] {taskinstance.py:1356} INFO - 
--------------------------------------------------------------------------------
[2024-04-02 17:17:02,285] {taskinstance.py:1357} INFO - Starting attempt 1 of 1
[2024-04-02 17:17:02,285] {taskinstance.py:1358} INFO - 
--------------------------------------------------------------------------------
[2024-04-02 17:17:02,990] {taskinstance.py:1377} INFO - Executing <Task(_PythonDecoratedOperator): GOOG> on 2024-01-16 00:00:00+00:00
[2024-04-02 17:17:03,075] {standard_task_runner.py:52} INFO - Started process 4338 to run task
[2024-04-02 17:17:03,374] {standard_task_runner.py:79} INFO - Running: ['airflow', 'tasks', 'run', 'get_stocks_dag', 'GOOG', 'scheduled__2024-01-16T00:00:00+00:00', '--job-id', '24', '--raw', '--subdir', 'DAGS_FOLDER/get_stocks.py', '--cfg-path', '/tmp/tmpc3zb3gio', '--error-file', '/tmp/tmpzvk5bdy6']
[2024-04-02 17:17:03,450] {standard_task_runner.py:80} INFO - Job 24: Subtask GOOG
[2024-04-02 17:17:09,922] {task_command.py:370} INFO - Running <TaskInstance: get_stocks_dag.GOOG scheduled__2024-01-16T00:00:00+00:00 [running]> on host alexmend-virtual-machine
[2024-04-02 17:17:13,463] {taskinstance.py:1569} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=airflow
AIRFLOW_CTX_DAG_ID=get_stocks_dag
AIRFLOW_CTX_TASK_ID=GOOG
AIRFLOW_CTX_EXECUTION_DATE=2024-01-16T00:00:00+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2024-01-16T00:00:00+00:00
[2024-04-02 17:17:18,459] {taskinstance.py:1889} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/alexmend/Documents/airflowalex/venv/lib/python3.9/site-packages/airflow/decorators/base.py", line 179, in execute
    return_value = super().execute(context)
  File "/home/alexmend/Documents/airflowalex/venv/lib/python3.9/site-packages/airflow/operators/python.py", line 171, in execute
    return_value = self.execute_callable()
  File "/home/alexmend/Documents/airflowalex/venv/lib/python3.9/site-packages/airflow/operators/python.py", line 189, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/home/alexmend/Documents/airflowalex/dags/get_stocks.py", line 18, in get_history
    yfinance.Ticker(ticker).history(
  File "/home/alexmend/Documents/airflowalex/venv/lib/python3.9/site-packages/yfinance/utils.py", line 103, in wrapper
    result = func(*args, **kwargs)
  File "/home/alexmend/Documents/airflowalex/venv/lib/python3.9/site-packages/yfinance/base.py", line 77, in history
    return self._lazy_load_price_history().history(*args, **kwargs)
  File "/home/alexmend/Documents/airflowalex/venv/lib/python3.9/site-packages/yfinance/utils.py", line 103, in wrapper
    result = func(*args, **kwargs)
  File "/home/alexmend/Documents/airflowalex/venv/lib/python3.9/site-packages/yfinance/scrapers/history.py", line 226, in history
    logger.debug(f'{self.ticker}: yfinance received OHLC data: {quotes.index[0]} -> {quotes.index[-1]}')
  File "/home/alexmend/Documents/airflowalex/venv/lib/python3.9/site-packages/pandas/core/indexes/base.py", line 5389, in __getitem__
    return getitem(key)
  File "/home/alexmend/Documents/airflowalex/venv/lib/python3.9/site-packages/pandas/core/arrays/datetimelike.py", line 379, in __getitem__
    result = cast("Union[Self, DTScalarOrNaT]", super().__getitem__(key))
  File "/home/alexmend/Documents/airflowalex/venv/lib/python3.9/site-packages/pandas/core/arrays/_mixins.py", line 284, in __getitem__
    result = self._ndarray[key]
IndexError: index 0 is out of bounds for axis 0 with size 0
[2024-04-02 17:17:18,608] {taskinstance.py:1395} INFO - Marking task as FAILED. dag_id=get_stocks_dag, task_id=GOOG, execution_date=20240116T000000, start_date=20240402T201702, end_date=20240402T201718
[2024-04-02 17:17:18,818] {standard_task_runner.py:92} ERROR - Failed to execute job 24 for task GOOG (index 0 is out of bounds for axis 0 with size 0; 4338)
[2024-04-02 17:17:19,054] {local_task_job.py:156} INFO - Task exited with return code 1
[2024-04-02 17:17:19,188] {local_task_job.py:273} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-04-02 17:42:47,798] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: get_stocks_dag.GOOG scheduled__2024-01-16T00:00:00+00:00 [queued]>
[2024-04-02 17:42:47,830] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: get_stocks_dag.GOOG scheduled__2024-01-16T00:00:00+00:00 [queued]>
[2024-04-02 17:42:47,831] {taskinstance.py:1356} INFO - 
--------------------------------------------------------------------------------
[2024-04-02 17:42:47,831] {taskinstance.py:1357} INFO - Starting attempt 1 of 1
[2024-04-02 17:42:47,831] {taskinstance.py:1358} INFO - 
--------------------------------------------------------------------------------
[2024-04-02 17:42:47,885] {taskinstance.py:1377} INFO - Executing <Task(_PythonDecoratedOperator): GOOG> on 2024-01-16 00:00:00+00:00
[2024-04-02 17:42:47,892] {standard_task_runner.py:52} INFO - Started process 19051 to run task
[2024-04-02 17:42:47,901] {standard_task_runner.py:79} INFO - Running: ['airflow', 'tasks', 'run', 'get_stocks_dag', 'GOOG', 'scheduled__2024-01-16T00:00:00+00:00', '--job-id', '293', '--raw', '--subdir', 'DAGS_FOLDER/get_stocks.py', '--cfg-path', '/tmp/tmpmbg_tefj', '--error-file', '/tmp/tmp4mukb538']
[2024-04-02 17:42:47,902] {standard_task_runner.py:80} INFO - Job 293: Subtask GOOG
[2024-04-02 17:42:48,030] {task_command.py:370} INFO - Running <TaskInstance: get_stocks_dag.GOOG scheduled__2024-01-16T00:00:00+00:00 [running]> on host alexmend-virtual-machine
[2024-04-02 17:42:48,179] {taskinstance.py:1569} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=airflow
AIRFLOW_CTX_DAG_ID=get_stocks_dag
AIRFLOW_CTX_TASK_ID=GOOG
AIRFLOW_CTX_EXECUTION_DATE=2024-01-16T00:00:00+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2024-01-16T00:00:00+00:00
[2024-04-02 17:42:48,769] {taskinstance.py:1889} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/alexmend/Documents/airflowalex/venv/lib/python3.9/site-packages/airflow/decorators/base.py", line 179, in execute
    return_value = super().execute(context)
  File "/home/alexmend/Documents/airflowalex/venv/lib/python3.9/site-packages/airflow/operators/python.py", line 171, in execute
    return_value = self.execute_callable()
  File "/home/alexmend/Documents/airflowalex/venv/lib/python3.9/site-packages/airflow/operators/python.py", line 189, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/home/alexmend/Documents/airflowalex/dags/get_stocks.py", line 18, in get_history
    yfinance.Ticker(ticker).history(
  File "/home/alexmend/Documents/airflowalex/venv/lib/python3.9/site-packages/yfinance/utils.py", line 103, in wrapper
    result = func(*args, **kwargs)
  File "/home/alexmend/Documents/airflowalex/venv/lib/python3.9/site-packages/yfinance/base.py", line 77, in history
    return self._lazy_load_price_history().history(*args, **kwargs)
  File "/home/alexmend/Documents/airflowalex/venv/lib/python3.9/site-packages/yfinance/utils.py", line 103, in wrapper
    result = func(*args, **kwargs)
  File "/home/alexmend/Documents/airflowalex/venv/lib/python3.9/site-packages/yfinance/scrapers/history.py", line 226, in history
    logger.debug(f'{self.ticker}: yfinance received OHLC data: {quotes.index[0]} -> {quotes.index[-1]}')
  File "/home/alexmend/Documents/airflowalex/venv/lib/python3.9/site-packages/pandas/core/indexes/base.py", line 5389, in __getitem__
    return getitem(key)
  File "/home/alexmend/Documents/airflowalex/venv/lib/python3.9/site-packages/pandas/core/arrays/datetimelike.py", line 379, in __getitem__
    result = cast("Union[Self, DTScalarOrNaT]", super().__getitem__(key))
  File "/home/alexmend/Documents/airflowalex/venv/lib/python3.9/site-packages/pandas/core/arrays/_mixins.py", line 284, in __getitem__
    result = self._ndarray[key]
IndexError: index 0 is out of bounds for axis 0 with size 0
[2024-04-02 17:42:48,798] {taskinstance.py:1395} INFO - Marking task as FAILED. dag_id=get_stocks_dag, task_id=GOOG, execution_date=20240116T000000, start_date=20240402T204247, end_date=20240402T204248
[2024-04-02 17:42:48,814] {standard_task_runner.py:92} ERROR - Failed to execute job 293 for task GOOG (index 0 is out of bounds for axis 0 with size 0; 19051)
[2024-04-02 17:42:48,840] {local_task_job.py:156} INFO - Task exited with return code 1
[2024-04-02 17:42:48,896] {local_task_job.py:273} INFO - 0 downstream tasks scheduled from follow-on schedule check
