[2024-04-02 13:06:44,820] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: get_stocks_dag.MSFT scheduled__2024-02-20T00:00:00+00:00 [queued]>
[2024-04-02 13:06:44,832] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: get_stocks_dag.MSFT scheduled__2024-02-20T00:00:00+00:00 [queued]>
[2024-04-02 13:06:44,833] {taskinstance.py:1356} INFO - 
--------------------------------------------------------------------------------
[2024-04-02 13:06:44,834] {taskinstance.py:1357} INFO - Starting attempt 1 of 1
[2024-04-02 13:06:44,834] {taskinstance.py:1358} INFO - 
--------------------------------------------------------------------------------
[2024-04-02 13:06:44,865] {taskinstance.py:1377} INFO - Executing <Task(_PythonDecoratedOperator): MSFT> on 2024-02-20 00:00:00+00:00
[2024-04-02 13:06:44,871] {standard_task_runner.py:52} INFO - Started process 11250 to run task
[2024-04-02 13:06:44,876] {standard_task_runner.py:79} INFO - Running: ['airflow', 'tasks', 'run', 'get_stocks_dag', 'MSFT', 'scheduled__2024-02-20T00:00:00+00:00', '--job-id', '148', '--raw', '--subdir', 'DAGS_FOLDER/get_stocks.py', '--cfg-path', '/tmp/tmpdemmwo09', '--error-file', '/tmp/tmpo53hzmur']
[2024-04-02 13:06:44,877] {standard_task_runner.py:80} INFO - Job 148: Subtask MSFT
[2024-04-02 13:06:44,938] {task_command.py:370} INFO - Running <TaskInstance: get_stocks_dag.MSFT scheduled__2024-02-20T00:00:00+00:00 [running]> on host alexmend-virtual-machine
[2024-04-02 13:06:45,011] {taskinstance.py:1569} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=airflow
AIRFLOW_CTX_DAG_ID=get_stocks_dag
AIRFLOW_CTX_TASK_ID=MSFT
AIRFLOW_CTX_EXECUTION_DATE=2024-02-20T00:00:00+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2024-02-20T00:00:00+00:00
[2024-04-02 13:06:45,948] {history.py:222} ERROR - MSFT: No price data found, symbol may be delisted (1h 2024-02-19 -> 2024-02-20)
[2024-04-02 13:06:45,953] {python.py:173} INFO - Done. Returned value was: None
[2024-04-02 13:06:45,963] {taskinstance.py:1395} INFO - Marking task as SUCCESS. dag_id=get_stocks_dag, task_id=MSFT, execution_date=20240220T000000, start_date=20240402T160644, end_date=20240402T160645
[2024-04-02 13:06:46,023] {local_task_job.py:156} INFO - Task exited with return code 0
[2024-04-02 13:06:46,052] {local_task_job.py:273} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-04-02 17:18:46,020] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: get_stocks_dag.MSFT scheduled__2024-02-20T00:00:00+00:00 [queued]>
[2024-04-02 17:18:46,054] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: get_stocks_dag.MSFT scheduled__2024-02-20T00:00:00+00:00 [queued]>
[2024-04-02 17:18:46,054] {taskinstance.py:1356} INFO - 
--------------------------------------------------------------------------------
[2024-04-02 17:18:46,054] {taskinstance.py:1357} INFO - Starting attempt 1 of 1
[2024-04-02 17:18:46,054] {taskinstance.py:1358} INFO - 
--------------------------------------------------------------------------------
[2024-04-02 17:18:46,164] {taskinstance.py:1377} INFO - Executing <Task(_PythonDecoratedOperator): MSFT> on 2024-02-20 00:00:00+00:00
[2024-04-02 17:18:46,314] {standard_task_runner.py:52} INFO - Started process 6994 to run task
[2024-04-02 17:18:46,318] {standard_task_runner.py:79} INFO - Running: ['airflow', 'tasks', 'run', 'get_stocks_dag', 'MSFT', 'scheduled__2024-02-20T00:00:00+00:00', '--job-id', '129', '--raw', '--subdir', 'DAGS_FOLDER/get_stocks.py', '--cfg-path', '/tmp/tmpxsce76hq', '--error-file', '/tmp/tmpzt_x7t97']
[2024-04-02 17:18:46,343] {standard_task_runner.py:80} INFO - Job 129: Subtask MSFT
[2024-04-02 17:18:46,991] {task_command.py:370} INFO - Running <TaskInstance: get_stocks_dag.MSFT scheduled__2024-02-20T00:00:00+00:00 [running]> on host alexmend-virtual-machine
[2024-04-02 17:18:47,845] {taskinstance.py:1569} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=airflow
AIRFLOW_CTX_DAG_ID=get_stocks_dag
AIRFLOW_CTX_TASK_ID=MSFT
AIRFLOW_CTX_EXECUTION_DATE=2024-02-20T00:00:00+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2024-02-20T00:00:00+00:00
[2024-04-02 17:18:48,912] {taskinstance.py:1889} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/alexmend/Documents/airflowalex/venv/lib/python3.9/site-packages/airflow/decorators/base.py", line 179, in execute
    return_value = super().execute(context)
  File "/home/alexmend/Documents/airflowalex/venv/lib/python3.9/site-packages/airflow/operators/python.py", line 171, in execute
    return_value = self.execute_callable()
  File "/home/alexmend/Documents/airflowalex/venv/lib/python3.9/site-packages/airflow/operators/python.py", line 189, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/home/alexmend/Documents/airflowalex/dags/get_stocks.py", line 18, in get_history
    yfinance.Ticker(ticker).history(
  File "/home/alexmend/Documents/airflowalex/venv/lib/python3.9/site-packages/yfinance/utils.py", line 103, in wrapper
    result = func(*args, **kwargs)
  File "/home/alexmend/Documents/airflowalex/venv/lib/python3.9/site-packages/yfinance/base.py", line 77, in history
    return self._lazy_load_price_history().history(*args, **kwargs)
  File "/home/alexmend/Documents/airflowalex/venv/lib/python3.9/site-packages/yfinance/utils.py", line 103, in wrapper
    result = func(*args, **kwargs)
  File "/home/alexmend/Documents/airflowalex/venv/lib/python3.9/site-packages/yfinance/scrapers/history.py", line 226, in history
    logger.debug(f'{self.ticker}: yfinance received OHLC data: {quotes.index[0]} -> {quotes.index[-1]}')
  File "/home/alexmend/Documents/airflowalex/venv/lib/python3.9/site-packages/pandas/core/indexes/base.py", line 5389, in __getitem__
    return getitem(key)
  File "/home/alexmend/Documents/airflowalex/venv/lib/python3.9/site-packages/pandas/core/arrays/datetimelike.py", line 379, in __getitem__
    result = cast("Union[Self, DTScalarOrNaT]", super().__getitem__(key))
  File "/home/alexmend/Documents/airflowalex/venv/lib/python3.9/site-packages/pandas/core/arrays/_mixins.py", line 284, in __getitem__
    result = self._ndarray[key]
IndexError: index 0 is out of bounds for axis 0 with size 0
[2024-04-02 17:18:49,086] {taskinstance.py:1395} INFO - Marking task as FAILED. dag_id=get_stocks_dag, task_id=MSFT, execution_date=20240220T000000, start_date=20240402T201846, end_date=20240402T201849
[2024-04-02 17:18:49,666] {standard_task_runner.py:92} ERROR - Failed to execute job 129 for task MSFT (index 0 is out of bounds for axis 0 with size 0; 6994)
[2024-04-02 17:18:49,809] {local_task_job.py:156} INFO - Task exited with return code 1
[2024-04-02 17:18:50,031] {local_task_job.py:273} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-04-02 17:45:09,523] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: get_stocks_dag.MSFT scheduled__2024-02-20T00:00:00+00:00 [queued]>
[2024-04-02 17:45:09,542] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: get_stocks_dag.MSFT scheduled__2024-02-20T00:00:00+00:00 [queued]>
[2024-04-02 17:45:09,543] {taskinstance.py:1356} INFO - 
--------------------------------------------------------------------------------
[2024-04-02 17:45:09,544] {taskinstance.py:1357} INFO - Starting attempt 1 of 1
[2024-04-02 17:45:09,544] {taskinstance.py:1358} INFO - 
--------------------------------------------------------------------------------
[2024-04-02 17:45:09,567] {taskinstance.py:1377} INFO - Executing <Task(_PythonDecoratedOperator): MSFT> on 2024-02-20 00:00:00+00:00
[2024-04-02 17:45:09,578] {standard_task_runner.py:52} INFO - Started process 21987 to run task
[2024-04-02 17:45:09,591] {standard_task_runner.py:79} INFO - Running: ['airflow', 'tasks', 'run', 'get_stocks_dag', 'MSFT', 'scheduled__2024-02-20T00:00:00+00:00', '--job-id', '392', '--raw', '--subdir', 'DAGS_FOLDER/get_stocks.py', '--cfg-path', '/tmp/tmp7mdwvxor', '--error-file', '/tmp/tmplj_rgn78']
[2024-04-02 17:45:09,594] {standard_task_runner.py:80} INFO - Job 392: Subtask MSFT
[2024-04-02 17:45:09,741] {task_command.py:370} INFO - Running <TaskInstance: get_stocks_dag.MSFT scheduled__2024-02-20T00:00:00+00:00 [running]> on host alexmend-virtual-machine
[2024-04-02 17:45:09,927] {taskinstance.py:1569} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=airflow
AIRFLOW_CTX_DAG_ID=get_stocks_dag
AIRFLOW_CTX_TASK_ID=MSFT
AIRFLOW_CTX_EXECUTION_DATE=2024-02-20T00:00:00+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2024-02-20T00:00:00+00:00
[2024-04-02 17:45:10,481] {taskinstance.py:1889} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/alexmend/Documents/airflowalex/venv/lib/python3.9/site-packages/airflow/decorators/base.py", line 179, in execute
    return_value = super().execute(context)
  File "/home/alexmend/Documents/airflowalex/venv/lib/python3.9/site-packages/airflow/operators/python.py", line 171, in execute
    return_value = self.execute_callable()
  File "/home/alexmend/Documents/airflowalex/venv/lib/python3.9/site-packages/airflow/operators/python.py", line 189, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/home/alexmend/Documents/airflowalex/dags/get_stocks.py", line 18, in get_history
    yfinance.Ticker(ticker).history(
  File "/home/alexmend/Documents/airflowalex/venv/lib/python3.9/site-packages/yfinance/utils.py", line 103, in wrapper
    result = func(*args, **kwargs)
  File "/home/alexmend/Documents/airflowalex/venv/lib/python3.9/site-packages/yfinance/base.py", line 77, in history
    return self._lazy_load_price_history().history(*args, **kwargs)
  File "/home/alexmend/Documents/airflowalex/venv/lib/python3.9/site-packages/yfinance/utils.py", line 103, in wrapper
    result = func(*args, **kwargs)
  File "/home/alexmend/Documents/airflowalex/venv/lib/python3.9/site-packages/yfinance/scrapers/history.py", line 226, in history
    logger.debug(f'{self.ticker}: yfinance received OHLC data: {quotes.index[0]} -> {quotes.index[-1]}')
  File "/home/alexmend/Documents/airflowalex/venv/lib/python3.9/site-packages/pandas/core/indexes/base.py", line 5389, in __getitem__
    return getitem(key)
  File "/home/alexmend/Documents/airflowalex/venv/lib/python3.9/site-packages/pandas/core/arrays/datetimelike.py", line 379, in __getitem__
    result = cast("Union[Self, DTScalarOrNaT]", super().__getitem__(key))
  File "/home/alexmend/Documents/airflowalex/venv/lib/python3.9/site-packages/pandas/core/arrays/_mixins.py", line 284, in __getitem__
    result = self._ndarray[key]
IndexError: index 0 is out of bounds for axis 0 with size 0
[2024-04-02 17:45:10,499] {taskinstance.py:1395} INFO - Marking task as FAILED. dag_id=get_stocks_dag, task_id=MSFT, execution_date=20240220T000000, start_date=20240402T204509, end_date=20240402T204510
[2024-04-02 17:45:10,513] {standard_task_runner.py:92} ERROR - Failed to execute job 392 for task MSFT (index 0 is out of bounds for axis 0 with size 0; 21987)
[2024-04-02 17:45:10,528] {local_task_job.py:156} INFO - Task exited with return code 1
[2024-04-02 17:45:10,581] {local_task_job.py:273} INFO - 0 downstream tasks scheduled from follow-on schedule check
