[2024-04-02 12:56:20,935] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: get_stocks_dag.TSLA scheduled__2024-01-02T00:00:00+00:00 [queued]>
[2024-04-02 12:56:20,946] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: get_stocks_dag.TSLA scheduled__2024-01-02T00:00:00+00:00 [queued]>
[2024-04-02 12:56:20,946] {taskinstance.py:1356} INFO - 
--------------------------------------------------------------------------------
[2024-04-02 12:56:20,946] {taskinstance.py:1357} INFO - Starting attempt 1 of 1
[2024-04-02 12:56:20,946] {taskinstance.py:1358} INFO - 
--------------------------------------------------------------------------------
[2024-04-02 12:56:20,975] {taskinstance.py:1377} INFO - Executing <Task(_PythonDecoratedOperator): TSLA> on 2024-01-02 00:00:00+00:00
[2024-04-02 12:56:20,981] {standard_task_runner.py:52} INFO - Started process 7836 to run task
[2024-04-02 12:56:20,987] {standard_task_runner.py:79} INFO - Running: ['airflow', 'tasks', 'run', 'get_stocks_dag', 'TSLA', 'scheduled__2024-01-02T00:00:00+00:00', '--job-id', '10', '--raw', '--subdir', 'DAGS_FOLDER/get_stocks.py', '--cfg-path', '/tmp/tmpqt53_a0g', '--error-file', '/tmp/tmp4n85u7jk']
[2024-04-02 12:56:20,988] {standard_task_runner.py:80} INFO - Job 10: Subtask TSLA
[2024-04-02 12:56:21,064] {task_command.py:370} INFO - Running <TaskInstance: get_stocks_dag.TSLA scheduled__2024-01-02T00:00:00+00:00 [running]> on host alexmend-virtual-machine
[2024-04-02 12:56:21,150] {taskinstance.py:1569} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=airflow
AIRFLOW_CTX_DAG_ID=get_stocks_dag
AIRFLOW_CTX_TASK_ID=TSLA
AIRFLOW_CTX_EXECUTION_DATE=2024-01-02T00:00:00+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2024-01-02T00:00:00+00:00
[2024-04-02 12:56:22,006] {history.py:222} ERROR - TSLA: No price data found, symbol may be delisted (1h 2024-01-01 -> 2024-01-02)
[2024-04-02 12:56:22,012] {python.py:173} INFO - Done. Returned value was: None
[2024-04-02 12:56:22,029] {taskinstance.py:1395} INFO - Marking task as SUCCESS. dag_id=get_stocks_dag, task_id=TSLA, execution_date=20240102T000000, start_date=20240402T155620, end_date=20240402T155622
[2024-04-02 12:56:22,091] {local_task_job.py:156} INFO - Task exited with return code 0
[2024-04-02 12:56:22,116] {local_task_job.py:273} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-04-02 17:41:33,602] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: get_stocks_dag.TSLA scheduled__2024-01-02T00:00:00+00:00 [queued]>
[2024-04-02 17:41:33,632] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: get_stocks_dag.TSLA scheduled__2024-01-02T00:00:00+00:00 [queued]>
[2024-04-02 17:41:33,632] {taskinstance.py:1356} INFO - 
--------------------------------------------------------------------------------
[2024-04-02 17:41:33,632] {taskinstance.py:1357} INFO - Starting attempt 1 of 1
[2024-04-02 17:41:33,632] {taskinstance.py:1358} INFO - 
--------------------------------------------------------------------------------
[2024-04-02 17:41:33,665] {taskinstance.py:1377} INFO - Executing <Task(_PythonDecoratedOperator): TSLA> on 2024-01-02 00:00:00+00:00
[2024-04-02 17:41:33,678] {standard_task_runner.py:52} INFO - Started process 17863 to run task
[2024-04-02 17:41:33,689] {standard_task_runner.py:79} INFO - Running: ['airflow', 'tasks', 'run', 'get_stocks_dag', 'TSLA', 'scheduled__2024-01-02T00:00:00+00:00', '--job-id', '253', '--raw', '--subdir', 'DAGS_FOLDER/get_stocks.py', '--cfg-path', '/tmp/tmpwjmwxc4b', '--error-file', '/tmp/tmp4rogriq1']
[2024-04-02 17:41:33,692] {standard_task_runner.py:80} INFO - Job 253: Subtask TSLA
[2024-04-02 17:41:33,847] {task_command.py:370} INFO - Running <TaskInstance: get_stocks_dag.TSLA scheduled__2024-01-02T00:00:00+00:00 [running]> on host alexmend-virtual-machine
[2024-04-02 17:41:33,998] {taskinstance.py:1569} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=airflow
AIRFLOW_CTX_DAG_ID=get_stocks_dag
AIRFLOW_CTX_TASK_ID=TSLA
AIRFLOW_CTX_EXECUTION_DATE=2024-01-02T00:00:00+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2024-01-02T00:00:00+00:00
[2024-04-02 17:41:34,657] {taskinstance.py:1889} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/alexmend/Documents/airflowalex/venv/lib/python3.9/site-packages/airflow/decorators/base.py", line 179, in execute
    return_value = super().execute(context)
  File "/home/alexmend/Documents/airflowalex/venv/lib/python3.9/site-packages/airflow/operators/python.py", line 171, in execute
    return_value = self.execute_callable()
  File "/home/alexmend/Documents/airflowalex/venv/lib/python3.9/site-packages/airflow/operators/python.py", line 189, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/home/alexmend/Documents/airflowalex/dags/get_stocks.py", line 18, in get_history
    yfinance.Ticker(ticker).history(
  File "/home/alexmend/Documents/airflowalex/venv/lib/python3.9/site-packages/yfinance/utils.py", line 103, in wrapper
    result = func(*args, **kwargs)
  File "/home/alexmend/Documents/airflowalex/venv/lib/python3.9/site-packages/yfinance/base.py", line 77, in history
    return self._lazy_load_price_history().history(*args, **kwargs)
  File "/home/alexmend/Documents/airflowalex/venv/lib/python3.9/site-packages/yfinance/utils.py", line 103, in wrapper
    result = func(*args, **kwargs)
  File "/home/alexmend/Documents/airflowalex/venv/lib/python3.9/site-packages/yfinance/scrapers/history.py", line 226, in history
    logger.debug(f'{self.ticker}: yfinance received OHLC data: {quotes.index[0]} -> {quotes.index[-1]}')
  File "/home/alexmend/Documents/airflowalex/venv/lib/python3.9/site-packages/pandas/core/indexes/base.py", line 5389, in __getitem__
    return getitem(key)
  File "/home/alexmend/Documents/airflowalex/venv/lib/python3.9/site-packages/pandas/core/arrays/datetimelike.py", line 379, in __getitem__
    result = cast("Union[Self, DTScalarOrNaT]", super().__getitem__(key))
  File "/home/alexmend/Documents/airflowalex/venv/lib/python3.9/site-packages/pandas/core/arrays/_mixins.py", line 284, in __getitem__
    result = self._ndarray[key]
IndexError: index 0 is out of bounds for axis 0 with size 0
[2024-04-02 17:41:34,696] {taskinstance.py:1395} INFO - Marking task as FAILED. dag_id=get_stocks_dag, task_id=TSLA, execution_date=20240102T000000, start_date=20240402T204133, end_date=20240402T204134
[2024-04-02 17:41:34,724] {standard_task_runner.py:92} ERROR - Failed to execute job 253 for task TSLA (index 0 is out of bounds for axis 0 with size 0; 17863)
[2024-04-02 17:41:34,751] {local_task_job.py:156} INFO - Task exited with return code 1
[2024-04-02 17:41:34,837] {local_task_job.py:273} INFO - 0 downstream tasks scheduled from follow-on schedule check
